services:
  - type: web
    name: kapekalakal-frontend
    env: node
    buildCommand: npm install && npm run build
    staticPublishPath: "./build"
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: NPM_VERSION
        value: 9.x
      - key: CI
        value: false
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    autoDeploy: true
